name: "AI PR Reviewer"
description: "Run an AI-based review on a pull request and post a comment with the results."

inputs:
  openai_api_key:
    description: 'OpenAI API key.'
    required: true
  github_token:
    description: 'GitHub token.'
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Get PR number from comment
      id: get-pr
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const prNumber = context.issue.number;
          const { data: pr } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber
          });
          
          core.setOutput('pr-number', prNumber);
          core.setOutput('base-ref', pr.base.ref);
          core.setOutput('head-ref', pr.head.ref);
          return prNumber;

    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.get-pr.outputs.head-ref }}
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies and build
      shell: bash
      working-directory: ${{ github.action_path }}
      run: npm ci && npm run build

    - name: Get PR diff
      shell: bash
      run: |
        git diff origin/${{ steps.get-pr.outputs.base-ref }}...HEAD > pr.diff
        echo "Diff saved to pr.diff"

    - name: Run AI review
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        PR_NUMBER: ${{ steps.get-pr.outputs.pr-number }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        BASE_REF: ${{ steps.get-pr.outputs.base-ref }}
        HEAD_REF: ${{ steps.get-pr.outputs.head-ref }}
      run: |
        node ${{ github.action_path }}/dist/reviewPr.js